# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.
from snakemake.utils import min_version

min_version("7.20")


configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/trimming.smk"
include: "rules/qc.smk"
include: "rules/ref.smk"
include: "rules/mapping.smk"
include: "rules/regions.smk"
include: "rules/candidate_calling.smk"
include: "rules/calling.smk"
include: "rules/phylogeny.smk"


rule all:
    input:
        get_final_output(),
