samples: config/samples.tsv

units: config/units.tsv

# currently only used for downloading known variation for BQSR,
# please ensure that this matches the genome downloaded in rule download_genome
ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 195
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 105
  # Genome build
  build: GRCh38

univec:
  activate: True
  core: True

### params section, alphabetically sorted

min_cov_for_candidate_sites: 4
min_cells_with_min_cov: 2

freebayes:
  min_alternate_fraction: 0.005
  chunksize: 200000

gatk:
  baserecalibrator: ""
  applybqsr: ""

picard:
  markduplicates: "--VALIDATION_STRINGENCY LENIENT"

raxml_ng:
  model: "GTGTR+FO+ASC_FELS{count_invariants}"
